from pathlib import Path

path = Path('src/pages/RulesPage.tsx')
text = path.read_text(encoding='utf-8')


def replace(old: str, new: str, expected: int = 1) -> None:
    global text
    count = text.count(old)
    if count != expected:
        raise RuntimeError(f'expected {expected} matches, got {count}: {old[:140]!r}')
    text = text.replace(old, new, expected)


replace(
'''import {
  FileText,
  Keyboard,
  ListPlus,
  Mouse,
  RotateCcw,
  Save,
  Trash2,
} from 'lucide-react';''',
'''import {
  RotateCcw,
  Save,
  Trash2,
} from 'lucide-react';''')

replace(
"import { ConfirmDialog } from '../components/ConfirmDialog';\n",
"import { ConfirmDialog } from '../components/ConfirmDialog';\nimport { TextPromptDialog } from '../components/TextPromptDialog';\nimport { RuleTreePanel, type FolderMoveTarget, type RuleMoveTarget } from '../components/rules/RuleTreePanel';\n")
replace(
"import type { FrontendAction, FrontendCondition, FrontendRule, FrontendTrigger } from '../lib/types';",
"import type { FrontendAction, FrontendCondition, FrontendRule, FrontendTrigger, RuleFolder } from '../lib/types';")

replace(
'''type EditorIntent =
  | { type: 'select'; id: string }
  | { type: 'new' };''',
'''type EditorIntent =
  | { type: 'select'; id: string }
  | { type: 'new'; folderId?: string | null };

type FolderPrompt =
  | { type: 'create'; parentId: string | null }
  | { type: 'rename'; folder: RuleFolder }
  | null;''')

# Remove left-list-only helpers that are no longer rendered. Search still uses
# formatTriggerType/condition/action labels below.
start = text.index('function isMouseTrigger(')
end = text.index('function formatConditionLabel(', start)
text = text[:start] + text[end:]

replace(
'''  const [pendingIntent, setPendingIntent] = useState<EditorIntent | null>(null);
  const [ruleToDelete, setRuleToDelete] = useState<FrontendRule | null>(null);
  const [saving, setSaving] = useState(false);''',
'''  const [pendingIntent, setPendingIntent] = useState<EditorIntent | null>(null);
  const [ruleToDelete, setRuleToDelete] = useState<FrontendRule | null>(null);
  const [folderPrompt, setFolderPrompt] = useState<FolderPrompt>(null);
  const [folderToDelete, setFolderToDelete] = useState<RuleFolder | null>(null);
  const [saving, setSaving] = useState(false);''')

replace(
'''  const openNewRule = () => {
    const next = makeNewRule(mode, activeProfile?.rules.length ?? 0);
    setSelectedRuleId(null);
    setDraftRule(next);
    setBaseline(JSON.stringify(next));
    setIsNewRule(true);
  };''',
'''  const openNewRule = (folderId: string | null = null) => {
    const siblingCount = activeProfile?.rules.filter((rule) => (rule.folderId ?? null) === folderId).length ?? 0;
    const next = { ...makeNewRule(mode, siblingCount), folderId };
    setSelectedRuleId(null);
    setDraftRule(next);
    setBaseline(JSON.stringify(next));
    setIsNewRule(true);
  };''')

replace(
'''    if (intent.type === 'new') {
      openNewRule();
      return;
    }''',
'''    if (intent.type === 'new') {
      openNewRule(intent.folderId ?? null);
      return;
    }''')

# Insert structure helpers before command/search effects.
marker = '''  useEffect(() => {
    const onSearch = (event: Event) => setQuery((event as CustomEvent<string>).detail ?? '');'''
helpers = r'''  const syncDraftMetadata = (nextRules: FrontendRule[]) => {
    if (!draftRule) return;
    const persisted = nextRules.find((rule) => rule.id === draftRule.id);
    if (!persisted) return;

    const patch = {
      enabled: persisted.enabled,
      folderId: persisted.folderId ?? null,
      order: persisted.order,
    };
    setDraftRule((current) => current?.id === persisted.id ? { ...current, ...patch } : current);
    if (baseline) {
      try {
        const parsed = JSON.parse(baseline) as FrontendRule;
        if (parsed.id === persisted.id) setBaseline(JSON.stringify({ ...parsed, ...patch }));
      } catch {
        // Baseline is internal JSON generated by this page; ignore impossible corruption.
      }
    }
  };

  const saveStructure = async (nextRules: FrontendRule[], nextFolders: RuleFolder[]) => {
    if (!activeProfile || saving) return false;
    setSaving(true);
    try {
      const saved = await saveProfile({ ...activeProfile, rules: nextRules, folders: nextFolders });
      if (saved) syncDraftMetadata(nextRules);
      return saved;
    } finally {
      setSaving(false);
    }
  };

  const createFolder = async (name: string, parentId: string | null) => {
    if (!activeProfile) return;
    const order = activeProfile.folders.filter((folder) => (folder.parentId ?? null) === parentId).length;
    const folder: RuleFolder = {
      id: crypto.randomUUID(),
      name,
      parentId,
      order,
    };
    if (await saveStructure(activeProfile.rules, [...activeProfile.folders, folder])) {
      setFolderPrompt(null);
    }
  };

  const renameFolder = async (folder: RuleFolder, name: string) => {
    if (!activeProfile) return;
    const nextFolders = activeProfile.folders.map((item) => item.id === folder.id ? { ...item, name } : item);
    if (await saveStructure(activeProfile.rules, nextFolders)) setFolderPrompt(null);
  };

  const deleteFolder = async (folder: RuleFolder) => {
    if (!activeProfile) return;
    const parentId = folder.parentId ?? null;
    const nextRules = activeProfile.rules.map((rule) =>
      (rule.folderId ?? null) === folder.id ? { ...rule, folderId: parentId } : rule,
    );
    const nextFolders = activeProfile.folders
      .filter((item) => item.id !== folder.id)
      .map((item) => (item.parentId ?? null) === folder.id ? { ...item, parentId } : item);
    if (await saveStructure(nextRules, nextFolders)) setFolderToDelete(null);
  };

  const duplicateRule = async (rule: FrontendRule) => {
    if (!activeProfile) return;
    const folderId = rule.folderId ?? null;
    const siblings = activeProfile.rules.filter((item) => (item.folderId ?? null) === folderId);
    const copy: FrontendRule = {
      ...structuredClone(rule),
      id: crypto.randomUUID(),
      name: rule.name?.trim()
        ? `${rule.name} ${t('rules.tree.copy_suffix', { defaultValue: '— копия' })}`
        : `${formatTriggerKey(rule.trigger)} ${t('rules.tree.copy_suffix', { defaultValue: '— копия' })}`,
      order: Math.max(-1, ...siblings.map((item) => item.order)) + 1,
    };
    await saveStructure([...activeProfile.rules, copy], activeProfile.folders);
  };

  const toggleRule = async (rule: FrontendRule) => {
    if (!activeProfile) return;
    const nextRules = activeProfile.rules.map((item) => item.id === rule.id ? { ...item, enabled: !item.enabled } : item);
    await saveStructure(nextRules, activeProfile.folders);
  };

  const moveRule = async (ruleId: string, target: RuleMoveTarget) => {
    if (!activeProfile) return;
    const moving = activeProfile.rules.find((rule) => rule.id === ruleId);
    if (!moving || target.beforeRuleId === ruleId) return;

    const sourceFolderId = moving.folderId ?? null;
    const targetFolderId = target.folderId ?? null;
    const updated = new Map<string, FrontendRule>();

    const sourceSiblings = activeProfile.rules
      .filter((rule) => rule.id !== ruleId && (rule.folderId ?? null) === sourceFolderId)
      .sort((a, b) => a.order - b.order);
    sourceSiblings.forEach((rule, index) => updated.set(rule.id, { ...rule, order: index }));

    const targetSiblings = activeProfile.rules
      .filter((rule) => rule.id !== ruleId && (rule.folderId ?? null) === targetFolderId)
      .sort((a, b) => a.order - b.order);
    let insertAt = target.beforeRuleId
      ? targetSiblings.findIndex((rule) => rule.id === target.beforeRuleId)
      : targetSiblings.length;
    if (insertAt < 0) insertAt = targetSiblings.length;
    targetSiblings.splice(insertAt, 0, { ...moving, folderId: targetFolderId });
    targetSiblings.forEach((rule, index) => updated.set(rule.id, { ...rule, folderId: targetFolderId, order: index }));

    const nextRules = activeProfile.rules.map((rule) => updated.get(rule.id) ?? rule);
    await saveStructure(nextRules, activeProfile.folders);
  };

  const moveFolder = async (folderId: string, target: FolderMoveTarget) => {
    if (!activeProfile || target.parentId === folderId || target.beforeFolderId === folderId) return;
    const moving = activeProfile.folders.find((folder) => folder.id === folderId);
    if (!moving) return;

    // Reject cycles: the target parent may not be a descendant of the moving folder.
    const byId = new Map(activeProfile.folders.map((folder) => [folder.id, folder]));
    let cursor = target.parentId;
    while (cursor) {
      if (cursor === folderId) return;
      cursor = byId.get(cursor)?.parentId ?? null;
    }

    const sourceParent = moving.parentId ?? null;
    const targetParent = target.parentId ?? null;
    const updated = new Map<string, RuleFolder>();

    const sourceSiblings = activeProfile.folders
      .filter((folder) => folder.id !== folderId && (folder.parentId ?? null) === sourceParent)
      .sort((a, b) => a.order - b.order);
    sourceSiblings.forEach((folder, index) => updated.set(folder.id, { ...folder, order: index }));

    const targetSiblings = activeProfile.folders
      .filter((folder) => folder.id !== folderId && (folder.parentId ?? null) === targetParent)
      .sort((a, b) => a.order - b.order);
    let insertAt = target.beforeFolderId
      ? targetSiblings.findIndex((folder) => folder.id === target.beforeFolderId)
      : targetSiblings.length;
    if (insertAt < 0) insertAt = targetSiblings.length;
    targetSiblings.splice(insertAt, 0, { ...moving, parentId: targetParent });
    targetSiblings.forEach((folder, index) => updated.set(folder.id, { ...folder, parentId: targetParent, order: index }));

    const nextFolders = activeProfile.folders.map((folder) => updated.get(folder.id) ?? folder);
    await saveStructure(activeProfile.rules, nextFolders);
  };

'''
if marker not in text:
    raise RuntimeError('search effect marker not found')
text = text.replace(marker, helpers + marker, 1)

# Toolbar add command stays root.
replace("requestIntent({ type: 'new' });", "requestIntent({ type: 'new', folderId: null });", expected=1)

# Replace entire old flat left section with compact tree component.
left_start = text.index('        <section className="w-[34%] min-w-[300px] max-w-[455px]')
right_start = text.index('        <section className="flex-1 min-w-0 flex flex-col bg-app-bg min-h-0">', left_start)
old_left = text[left_start:right_start]
new_left = '''        <RuleTreePanel
          title={viewTitle}
          rules={filteredRules}
          folders={activeProfile.folders}
          selectedRuleId={isNewRule ? null : selectedRuleId}
          query={query}
          saving={saving}
          onSelectRule={(rule) => requestIntent({ type: 'select', id: rule.id })}
          onCreateRule={(folderId) => requestIntent({ type: 'new', folderId })}
          onCreateFolder={(parentId) => setFolderPrompt({ type: 'create', parentId })}
          onRenameFolder={(folder) => setFolderPrompt({ type: 'rename', folder })}
          onDeleteFolder={(folder) => setFolderToDelete(folder)}
          onDuplicateRule={(rule) => void duplicateRule(rule)}
          onToggleRule={(rule) => void toggleRule(rule)}
          onDeleteRule={(rule) => setRuleToDelete(rule)}
          onMoveRule={(ruleId, target) => void moveRule(ruleId, target)}
          onMoveFolder={(folderId, target) => void moveFolder(folderId, target)}
        />

'''
text = text[:left_start] + new_left + text[right_start:]

# Add dialogs before fragment close, after existing rule delete ConfirmDialog.
closing = '''      <ConfirmDialog
        open={ruleToDelete !== null}
        title={t('rules.delete_rule')}
        message={t('rules.confirm_delete')}
        confirmLabel={t('profiles_menu.delete_btn')}
        danger
        onCancel={() => { if (!saving) setRuleToDelete(null); }}
        onConfirm={async () => {
          const rule = ruleToDelete;
          if (!rule) return;
          const beforeId = rule.id;
          await deleteRule(rule);
          const stillExists = useProfileStore.getState().profiles
            .find((profile) => profile.id === useProfileStore.getState().activeProfileId)
            ?.rules.some((item) => item.id === beforeId);
          if (!stillExists) setRuleToDelete(null);
        }}
      />
'''
addition = closing + '''
      <TextPromptDialog
        open={folderPrompt !== null}
        title={folderPrompt?.type === 'rename'
          ? t('rules.tree.rename_folder', { defaultValue: 'Переименовать папку' })
          : t('rules.tree.new_folder', { defaultValue: 'Новая папка' })}
        label={t('common.name', { defaultValue: 'Название' })}
        initialValue={folderPrompt?.type === 'rename' ? folderPrompt.folder.name : ''}
        placeholder={t('rules.tree.folder_name', { defaultValue: 'Название папки' })}
        confirmLabel={folderPrompt?.type === 'rename'
          ? t('common.save', { defaultValue: 'Сохранить' })
          : t('common.create', { defaultValue: 'Создать' })}
        cancelLabel={t('common.cancel', { defaultValue: 'Отмена' })}
        onCancel={() => { if (!saving) setFolderPrompt(null); }}
        onConfirm={async (name) => {
          const prompt = folderPrompt;
          if (!prompt) return;
          if (prompt.type === 'rename') await renameFolder(prompt.folder, name);
          else await createFolder(name, prompt.parentId);
        }}
      />

      <ConfirmDialog
        open={folderToDelete !== null}
        title={t('rules.tree.delete_folder', { defaultValue: 'Удалить папку' })}
        message={t('rules.tree.delete_folder_hint', { defaultValue: 'Правила и подпапки не удалятся — они будут перемещены на уровень выше.' })}
        confirmLabel={t('profiles_menu.delete_btn')}
        danger
        onCancel={() => { if (!saving) setFolderToDelete(null); }}
        onConfirm={async () => {
          const folder = folderToDelete;
          if (folder) await deleteFolder(folder);
        }}
      />
'''
replace(closing, addition)

path.write_text(text, encoding='utf-8')
print('compact tree integrated into RulesPage')
