//! KeyMaster Pro MCP bridge.
//!
//! The default `--mcp` mode is deliberately read-only. Mutating/executing tools
//! are advertised only when the process is started with `--mcp-write`.
//! Communication uses newline-delimited JSON-RPC over stdio so the same binary
//! can be launched by MCP clients without opening a network listener.

use serde::Deserialize;
use serde_json::{Map, Value, json};
use std::io::{BufRead, Write};

const MODERN_PROTOCOL: &str = "2026-07-28";
const LEGACY_PROTOCOL: &str = "2025-11-25";

#[derive(Debug, Deserialize)]
struct RpcRequest {
    #[allow(dead_code)]
    jsonrpc: Option<String>,
    #[serde(default)]
    id: Option<Value>,
    method: String,
    #[serde(default)]
    params: Option<Value>,
}

fn rpc_result(id: Value, result: Value) -> Value {
    json!({ "jsonrpc": "2.0", "id": id, "result": result })
}

fn rpc_error(id: Value, code: i64, message: impl Into<String>, data: Option<Value>) -> Value {
    let mut error = json!({ "code": code, "message": message.into() });
    if let Some(data) = data {
        error["data"] = data;
    }
    json!({ "jsonrpc": "2.0", "id": id, "error": error })
}

fn text_tool_result(value: Value) -> Value {
    let text = serde_json::to_string_pretty(&value).unwrap_or_else(|_| value.to_string());
    json!({
        "resultType": "complete",
        "content": [{ "type": "text", "text": text }],
        "structuredContent": value,
        "isError": false
    })
}

fn tool_error(message: impl Into<String>) -> Value {
    let message = message.into();
    json!({
        "resultType": "complete",
        "content": [{ "type": "text", "text": message }],
        "isError": true
    })
}

fn tool(
    name: &str,
    description: &str,
    properties: Value,
    required: &[&str],
    read_only: bool,
) -> Value {
    json!({
        "name": name,
        "description": description,
        "inputSchema": {
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": false
        },
        "annotations": {
            "readOnlyHint": read_only,
            "destructiveHint": false,
            "idempotentHint": read_only
        }
    })
}

fn tools(write_enabled: bool) -> Vec<Value> {
    let mut tools = vec![
        tool(
            "keymaster_list_profiles",
            "List KeyMaster profiles and compact counts. Does not modify anything.",
            json!({}),
            &[],
            true,
        ),
        tool(
            "keymaster_get_profile",
            "Read one KeyMaster profile including rules, macros, layers and folders. If id is omitted, returns the runtime-active profile.",
            json!({ "id": { "type": "string" } }),
            &[],
            true,
        ),
        tool(
            "keymaster_runtime_status",
            "Read active/preferred profile and auto-switch/manual-lock state.",
            json!({}),
            &[],
            true,
        ),
        tool(
            "keymaster_validate_rule",
            "Validate and normalize a complete KeyMaster rule object without saving it.",
            json!({ "rule": { "type": "object" } }),
            &["rule"],
            true,
        ),
    ];

    if write_enabled {
        tools.extend([
            tool(
                "keymaster_activate_profile",
                "Activate a KeyMaster profile. This changes the user's runtime and preferred profile.",
                json!({ "id": { "type": "string" } }),
                &["id"],
                false,
            ),
            tool(
                "keymaster_run_macro",
                "Run a named macro from a profile through the production macro preview path.",
                json!({
                    "macroId": { "type": "string" },
                    "profileId": { "type": "string" },
                    "speed": { "type": "number", "minimum": 0.05, "maximum": 20 },
                    "repeatCount": { "type": "integer", "minimum": 1, "maximum": 100 }
                }),
                &["macroId"],
                false,
            ),
            tool(
                "keymaster_apply_rule",
                "Validate and append one rule to a profile. A fresh rule id/order are generated by KeyMaster. Use only after the user has approved the proposed rule.",
                json!({
                    "profileId": { "type": "string" },
                    "rule": { "type": "object" }
                }),
                &["rule"],
                false,
            ),
        ]);
    }

    tools
}

async fn profile_list() -> Result<Value, String> {
    crate::daemon::ipc_client::call("profile.list", None).await
}

fn profiles_from_list(value: &Value) -> Result<Vec<crate::shared::types::Profile>, String> {
    serde_json::from_value(
        value
            .get("profiles")
            .cloned()
            .ok_or_else(|| "profile.list response has no profiles".to_string())?,
    )
    .map_err(|error| format!("Invalid profile.list payload: {error}"))
}

fn active_id_from_list(value: &Value) -> Option<String> {
    value.get("active").and_then(Value::as_str).map(str::to_string)
}

fn tool_args(params: Option<&Value>) -> Map<String, Value> {
    params
        .and_then(|value| value.get("arguments"))
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default()
}

fn validate_rule_references(
    rule: &crate::schemas::frontend::FrontendRule,
    profile: &crate::shared::types::Profile,
) -> Result<(), String> {
    use crate::schemas::frontend::{FrontendAction, FrontendCondition};

    let macro_ids: std::collections::HashSet<&str> =
        profile.macros.iter().map(|item| item.id.as_str()).collect();
    let layer_ids: std::collections::HashSet<&str> =
        profile.layers.iter().map(|item| item.id.as_str()).collect();

    for action in rule
        .actions
        .iter()
        .chain(rule.hold_actions.iter().flatten())
    {
        match action {
            FrontendAction::RunMacro { macro_id, .. } if !macro_ids.contains(macro_id.as_str()) => {
                return Err(format!("Unknown macroId: {macro_id}"));
            }
            FrontendAction::ToggleLayer { layer_id } | FrontendAction::HoldLayer { layer_id }
                if !layer_ids.contains(layer_id.as_str()) =>
            {
                return Err(format!("Unknown layerId: {layer_id}"));
            }
            _ => {}
        }
    }

    for condition in &rule.conditions {
        if let FrontendCondition::LayerActive { layer_id } = condition {
            if !layer_ids.contains(layer_id.as_str()) {
                return Err(format!("Unknown layerId: {layer_id}"));
            }
        }
    }
    Ok(())
}

fn normalize_rule_value(mut value: Value, order: i32) -> Result<crate::schemas::frontend::FrontendRule, String> {
    let object = value
        .as_object_mut()
        .ok_or_else(|| "rule must be an object".to_string())?;
    object.insert("id".to_string(), json!(uuid::Uuid::new_v4().to_string()));
    object.entry("priority".to_string()).or_insert(json!(10));
    object.entry("enabled".to_string()).or_insert(json!(true));
    object.entry("conditions".to_string()).or_insert(json!([]));
    object.entry("holdActions".to_string()).or_insert(Value::Null);
    object.entry("folderId".to_string()).or_insert(Value::Null);
    object.insert("order".to_string(), json!(order));
    serde_json::from_value(value).map_err(|error| format!("Invalid KeyMaster rule: {error}"))
}

async fn call_tool(name: &str, params: Option<&Value>, write_enabled: bool) -> Value {
    let args = tool_args(params);

    let result: Result<Value, String> = match name {
        "keymaster_list_profiles" => async {
            let list = profile_list().await?;
            let active = active_id_from_list(&list);
            let profiles = profiles_from_list(&list)?
                .into_iter()
                .map(|profile| {
                    json!({
                        "id": profile.id,
                        "name": profile.name,
                        "active": active.as_deref() == Some(profile.id.as_str()),
                        "isDefault": profile.is_default,
                        "rules": profile.rules.len(),
                        "macros": profile.macros.len(),
                        "layers": profile.layers.len()
                    })
                })
                .collect::<Vec<_>>();
            Ok(json!({ "profiles": profiles }))
        }
        .await,
        "keymaster_get_profile" => async {
            let list = profile_list().await?;
            let requested = args
                .get("id")
                .and_then(Value::as_str)
                .map(str::to_string)
                .or_else(|| active_id_from_list(&list))
                .ok_or_else(|| "No active profile".to_string())?;
            let profile = profiles_from_list(&list)?
                .into_iter()
                .find(|profile| profile.id == requested)
                .ok_or_else(|| format!("Profile not found: {requested}"))?;
            serde_json::to_value(profile).map_err(|error| error.to_string())
        }
        .await,
        "keymaster_runtime_status" => {
            crate::daemon::ipc_client::call("profile.runtime_status", None).await
        }
        "keymaster_validate_rule" => async {
            let rule_value = args
                .get("rule")
                .cloned()
                .ok_or_else(|| "Missing rule".to_string())?;
            let rule = normalize_rule_value(rule_value, 0)?;
            serde_json::to_value(rule).map_err(|error| error.to_string())
        }
        .await,
        "keymaster_activate_profile" if write_enabled => async {
            let id = args
                .get("id")
                .and_then(Value::as_str)
                .ok_or_else(|| "Missing id".to_string())?;
            crate::daemon::ipc_client::call("profile.activate", Some(json!({ "id": id }))).await
        }
        .await,
        "keymaster_run_macro" if write_enabled => async {
            let macro_id = args
                .get("macroId")
                .and_then(Value::as_str)
                .ok_or_else(|| "Missing macroId".to_string())?;
            let list = profile_list().await?;
            let profile_id = args
                .get("profileId")
                .and_then(Value::as_str)
                .map(str::to_string)
                .or_else(|| active_id_from_list(&list))
                .ok_or_else(|| "No active profile".to_string())?;
            let profile = profiles_from_list(&list)?
                .into_iter()
                .find(|profile| profile.id == profile_id)
                .ok_or_else(|| format!("Profile not found: {profile_id}"))?;
            let macro_def = profile
                .macros
                .into_iter()
                .find(|item| item.id == macro_id)
                .ok_or_else(|| format!("Macro not found: {macro_id}"))?;
            let speed = args.get("speed").and_then(Value::as_f64).unwrap_or(1.0).clamp(0.05, 20.0);
            let repeat_count = args
                .get("repeatCount")
                .and_then(Value::as_u64)
                .unwrap_or(1)
                .clamp(1, 100) as u32;
            crate::daemon::ipc_client::call(
                "macro.preview",
                Some(json!({
                    "steps": macro_def.steps,
                    "playback": {
                        "speed": speed,
                        "repeatCount": repeat_count,
                        "repeatWhileHeld": false
                    }
                })),
            )
            .await
        }
        .await,
        "keymaster_apply_rule" if write_enabled => async {
            let list = profile_list().await?;
            let profile_id = args
                .get("profileId")
                .and_then(Value::as_str)
                .map(str::to_string)
                .or_else(|| active_id_from_list(&list))
                .ok_or_else(|| "No active profile".to_string())?;
            let mut profile = profiles_from_list(&list)?
                .into_iter()
                .find(|profile| profile.id == profile_id)
                .ok_or_else(|| format!("Profile not found: {profile_id}"))?;
            let rule_value = args
                .get("rule")
                .cloned()
                .ok_or_else(|| "Missing rule".to_string())?;
            let rule = normalize_rule_value(rule_value, profile.rules.len() as i32)?;
            validate_rule_references(&rule, &profile)?;
            let result_rule = serde_json::to_value(&rule).map_err(|error| error.to_string())?;
            profile.rules.push(rule);
            crate::daemon::ipc_client::call(
                "profile.save",
                Some(serde_json::to_value(profile).map_err(|error| error.to_string())?),
            )
            .await?;
            Ok(json!({ "success": true, "rule": result_rule }))
        }
        .await,
        _ if !write_enabled
            && matches!(
                name,
                "keymaster_activate_profile" | "keymaster_run_macro" | "keymaster_apply_rule"
            ) => Err("This MCP process is read-only. Start KeyMaster with --mcp-write only when write/execute access is explicitly intended.".to_string()),
        _ => Err(format!("Unknown tool: {name}")),
    };

    match result {
        Ok(value) => text_tool_result(value),
        Err(error) => tool_error(error),
    }
}

async fn handle_request(request: RpcRequest, write_enabled: bool) -> Option<Value> {
    let id = request.id.clone();

    if request.method == "notifications/initialized" {
        return None;
    }

    let result = match request.method.as_str() {
        "server/discover" => Ok(json!({
            "resultType": "complete",
            "supportedVersions": [MODERN_PROTOCOL],
            "capabilities": { "tools": {} },
            "serverInfo": { "name": "KeyMaster Pro", "version": env!("CARGO_PKG_VERSION") },
            "instructions": if write_enabled {
                "KeyMaster automation bridge. Write/execute tools are enabled for this process. Prefer reading/validating first and only mutate after explicit user approval."
            } else {
                "KeyMaster automation bridge in read-only mode. Use it to inspect profiles/rules and validate proposed rules."
            },
            "ttlMs": 60_000,
            "cacheScope": "private"
        })),
        "initialize" => {
            let requested = request
                .params
                .as_ref()
                .and_then(|params| params.get("protocolVersion"))
                .and_then(Value::as_str)
                .unwrap_or(LEGACY_PROTOCOL);
            let negotiated = if matches!(requested, "2025-11-25" | "2025-06-18" | "2025-03-26" | "2024-11-05") {
                requested
            } else {
                LEGACY_PROTOCOL
            };
            Ok(json!({
                "protocolVersion": negotiated,
                "capabilities": { "tools": { "listChanged": false } },
                "serverInfo": { "name": "KeyMaster Pro", "version": env!("CARGO_PKG_VERSION") },
                "instructions": "KeyMaster automation bridge"
            }))
        }
        "tools/list" => Ok(json!({
            "resultType": "complete",
            "tools": tools(write_enabled),
            "ttlMs": 30_000,
            "cacheScope": "private"
        })),
        "tools/call" => {
            let name = request
                .params
                .as_ref()
                .and_then(|params| params.get("name"))
                .and_then(Value::as_str)
                .ok_or_else(|| "tools/call missing params.name".to_string());
            match name {
                Ok(name) => return id.map(|id| rpc_result(id, futures_lite_compat(call_tool(name, request.params.as_ref(), write_enabled)).await)),
                Err(error) => Err(error),
            }
        }
        _ => Err(format!("Method not found: {}", request.method)),
    };

    id.map(|id| match result {
        Ok(value) => rpc_result(id, value),
        Err(message) => rpc_error(id, -32601, message, None),
    })
}

// Tiny named helper keeps the `tools/call` branch readable while still awaiting
// the normal async tool result. It deliberately does no protocol transformation.
async fn futures_lite_compat<F>(future: F) -> Value
where
    F: std::future::Future<Output = Value>,
{
    future.await
}

pub fn run_stdio(write_enabled: bool) -> Result<(), String> {
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|error| format!("Failed to create MCP runtime: {error}"))?;

    let stdin = std::io::stdin();
    let mut stdout = std::io::stdout().lock();

    for line in stdin.lock().lines() {
        let line = line.map_err(|error| format!("MCP stdin error: {error}"))?;
        if line.trim().is_empty() {
            continue;
        }

        let response = match serde_json::from_str::<RpcRequest>(&line) {
            Ok(request) => runtime.block_on(handle_request(request, write_enabled)),
            Err(error) => Some(rpc_error(
                Value::Null,
                -32700,
                format!("Parse error: {error}"),
                None,
            )),
        };

        if let Some(response) = response {
            let encoded = serde_json::to_string(&response)
                .map_err(|error| format!("MCP response serialization failed: {error}"))?;
            stdout
                .write_all(encoded.as_bytes())
                .and_then(|_| stdout.write_all(b"\n"))
                .and_then(|_| stdout.flush())
                .map_err(|error| format!("MCP stdout error: {error}"))?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn read_only_tool_catalog_has_no_mutators() {
        let names = tools(false)
            .into_iter()
            .filter_map(|tool| tool.get("name").and_then(Value::as_str).map(str::to_string))
            .collect::<Vec<_>>();
        assert!(names.contains(&"keymaster_list_profiles".to_string()));
        assert!(!names.contains(&"keymaster_apply_rule".to_string()));
        assert!(!names.contains(&"keymaster_run_macro".to_string()));
    }

    #[test]
    fn write_tool_catalog_is_explicit() {
        let names = tools(true)
            .into_iter()
            .filter_map(|tool| tool.get("name").and_then(Value::as_str).map(str::to_string))
            .collect::<Vec<_>>();
        assert!(names.contains(&"keymaster_apply_rule".to_string()));
        assert!(names.contains(&"keymaster_run_macro".to_string()));
    }
}
